### ISSUE TITLE
Not all data files are in the same place

### ISSUE THREAD

**Issue by adamobeng** [datacarpentry/workshop-template-ARCHIVED#26]
The lessons page makes it seem like all the data files for the ecology lesson can be downloaded as a zip from figshare, but there is at least one in another place (on DropBox, https://www.dropbox.com/s/kbb4k00eanm19lg/Portal_rodents_19772002_scinameUUIDs.csv?dl=0). 

Could we put all the data files in a single, consistent, preferably self-hosted, place? This would be particularly helpful in preparing for workshops with poor or restricted internet connectivity.

**Comment by ethanwhite** [comment]
The figshare location is the official place for hosting the ecology data files. I don't believe that the UUID data ever became part of the main lessons so that link can probably be replaced/removed, but @tracykteal may have a better idea of what it's doing there.

**Comment by adamobeng** [comment]
The data file I linked to is required for the OpenRefine lesson, so I guess it should be moved to figshare?

**Comment by ethanwhite** [comment]
Ah, got it, thanks. Can you open a PR into https://github.com/weecology/portal-teachingdb (which is the intermediate step to figshare)?

**Comment by tracykteal** [comment]
Thanks @adamobeng. That data is now in same FigShare location.
