### ISSUE TITLE
link to GitHub importer fails

### ISSUE THREAD

**Issue by smcclatchy** [datacarpentry/workshop-template-ARCHIVED#31]
Hi,

The link to the GitHub import gives a 404: file not found error.

Thanks,

Sue

**Comment by tracykteal** [comment]
Thanks for adding this issue.

For me, it's going to that page, but it's not automatically filling in the information for the workshop-template repository.  So, you have to enter the cloning URL and a name for the repo. 

That might be a github change. Looking in to it.

**Comment by smcclatchy** [comment]
The Github importer defaults to the ErinBecker-workshoptemplate branch rather than gh-pages. I'm not sure if that's because it chooses alphabetically from the list of branches. It took me a while to figure out why I couldn't publish my workshop web page, then once I discovered the problem, how to fix it by changing the default remote branch.

**Comment by tracykteal** [comment]
Thanks @smcclatchy. Github importer was acting up for a bit. It seems better now, but you're right, it's defaulting to the first in the list, rather than the default branch in Settings. I fixed that by deleting the first branch in the list, so it's working fine now, although it's a bit of a hack.
