### ISSUE TITLE
All lesson html pages should have link to repo

### ISSUE THREAD

**Issue by kcranston** [datacarpentry/workshop-template-ARCHIVED#8]
For example, [this python lesson](http://datacarpentry.github.io/python-ecology) does not have a link to the [python repo](https://github.com/datacarpentry/python-ecology). This is a GitHub icon / link in the footer at the bottom of the page, but 1. that is really hidey; and 2. the link, at least for the python lesson, just goes back to the lesson, not the repo. 

Perhaps the classic 'Fork me on GitHub' banner at the top right?

**Comment by tracykteal** [comment]
We do have this now. Here it is rendered

http://www.datacarpentry.org/workshop-template/

I think this is an issue for the lesson template though, and it hasn't been added there. I'll make that issue and that fix.
